<H1><center><span style="color:#8c1c13">EXERCISES</span></center></H1>

![EXERCISES](img/1.gif)

1. [PYTHON CRASH COURSE](#1)
2. <strong>[NUMPY](#2)</strong>
3. <strong>[PANDAS](#3)</strong>
4. <strong>[MATPLOTLIB](#3)</strong>
5. <strong>[SEABORN](#3)</strong>

<a id=1>  </a> <br>

<h2>Python Crash Course Exercises</h2>

![python](img/python.gif)

<h3><span style="color:#742818">E1: What is 7 to the power of 4?</span></h3>

In [5]:
print(7**4)

2401


<h3><span style="color:#742818">E2: Split string into a list.</span></h3>

In [4]:
s = 'Hi there Sam!'
list1 = s.split()
list1

['Hi', 'there', 'Sam!']

<h3><span style="color:#742818">

E3: Use .format() to print the following string:

The diameter of Earth is 12742 kilometers.</span></h3>

In [6]:
planet = 'Earth'
diameter = 12742

print(f"The diameter of {planet} is {diameter} kilometers.")

The diameter of Earth is 12742 kilometers.


<h3><span style="color:#742818">E4: Given this nested list, use indexing to grab the word "hello"</span></h3>

In [9]:
lst = [1,2,[3,4],[5,[100,200,["hello"]],23,11],1,7]  # given nested list

#solution
lst[3][1][2]

['hello']

<h3><span style="color:#742818">E5: Given this nested dictionary grab the word "hello". Be prepared, this will be annoying/tricky</span></h3>

In [10]:
# given nested dictionary
d = {'k1': [1,2,3,{'tricky': ['oh','man','incepiton', {'target':[1,2,3,'hello']}]}]}

#solution
d['k1'][3]['tricky'][3]['target'][3]

'hello'

<h3><span style="color:#742818">E6: Create a function that grabs the email website domain from a string in the form: user@domain.com</span></h3>

**So for example, passing "user@domain.com" would return: domain.com**

In [11]:
def domainGet(s):
    return s.split('@')[-1]

# call the function
domainGet('user@domain.com')

'domain.com'

<h3><span style="color:#742818">E7: Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. </span></h3>

In [12]:
def findDog(s):
    return 'dog' in s.lower().split()

# call the function
findDog('Is there a dog here?')

True

<h3><span style="color:#742818">E8: Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. </span></h3>

In [13]:
def countDog(s):
    s = s.lower().split()
    i = 0
    count = 0
    while i < len(s):
        if s[i] == 'dog':
            count = count + 1
            i = i+1
        else:
            i = i+1
    print(count)

countDog('This dog runs faster than the other dog dude!')

2


<h3><span style="color:#742818">E9: Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'. </span></h3>

**For example: eq = ['soup','dog','salad','cat','great']**

<h3><span style="color:#742818">should be filtered down to:</span></h3>

**['soup' , 'salad']**


In [14]:
seq = ['soup','dog','salad','cat','great']

#find the words
withS = filter(lambda word: word.startswith('s'), seq)
print(list(withS))

['soup', 'salad']


<h3><span style="color:#742818">Final Problem: 
You are driving a little too fast, and a police officer stops you. Write a function to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". If your speed is 60 or less, the result is "No Ticket". If speed is between 61 and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all cases. </span></h3>

**Function Explanation**

1. speed = 60 or less . result = No Ticket
2. speed = 61 and 80, result = Small Ticket
3. speed = 81 or more, result = Big Ticket

- is_birthday = True or false
- on your birthday your speed can be 5 higher in all cases

In [15]:
#create function

def caught_speeding(speed, is_birthday):
    if is_birthday == True:
        if speed <= 65:
            return "No Ticket"
        elif speed in range(66,86):
            return "Small Ticket"
        else:
            return "Big Ticket"
    else:
        if speed <= 60:
            return "No Ticket"
        if speed in range(61,81):
            return "Small Ticket"
        else:
            return "Big Ticket"

In [18]:
#call the function

print(caught_speeding(81,True))
print(caught_speeding(81,False))

Small Ticket
Big Ticket


<a id=2>  </a> <br>

<h2>NumPy Exercises</h2>

![python](img/n.gif)

In [19]:
#import NumPy library

import numpy as np

<h3><span style="color:#065a60">Coding Exercise Check-in 1: Crating NumPy Arrays </span></h3>

**TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.**

In [20]:
myarray = np.linspace(0, 10, 101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

<h3><span style="color:#065a60">Coding Exercise Check-in 2: Selecting Data from NumPy Arrays </span></h3>

#### TASK: Use numpy to check how many rolls were greater than 2.
**For example if dice_rolls=[1,2,3] then the answer is 1..**

In [23]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1,
                       5, 1, 4, 2, 1, 4, 5, 3,
                       4, 5, 2, 4, 2, 6, 6, 3, 
                       6, 2, 3, 5, 6, 5])
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [24]:
gt2 = dice_rolls[dice_rolls > 2]
count = gt2.size
count

19

<h3><span style="color:#065a60">Coding Exercise Check-in 3: Operations on NumPy Arrays </span></h3>

**TASK: A bank account has had withdrawals and deposits tracked in a numpy array called account_transactions. 
Based on this list of account transactions, what is the total remaining in the account? 
Assign your answer to a variable called account_total. Please note, in order for the exercise to evaluate correctly, 
you must use the variable name account_total.**

In [25]:
account_transactions = np.array([500, 1000, -250, 430, -175, 
                               123, -987])

account_total = account_transactions.sum()
print(account_total)

641


<h3><span style="color:#065a60">E1: Create an array of 10 zeros.</span></h3>

In [26]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<h3><span style="color:#065a60">E2: Create an array of 10 ones.</span></h3>

In [28]:
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h3><span style="color:#065a60">E3: Create an array of 10 fives.</span></h3>

In [44]:
arr3 = np.full((10,),5)
arr3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

<h3><span style="color:#065a60">E4: Create an array of the integers from 10 to 50.</span></h3>

In [35]:
arr4 = np.arange(10,51)
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

<h3><span style="color:#065a60">E5: Create an array of all the even integers from 10 to 50.</span></h3>

In [34]:
arr5 = np.arange(10,51,2)
arr5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

<h3><span style="color:#065a60">E6: Create a 3x3 matrix with values ranging from 0 to 8.</span></h3>

In [33]:
arr6 = np.arange(0,9).reshape(3,3)
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h3><span style="color:#065a60">E7: Create a 3x3 identity matrix.</span></h3>

In [37]:
arr7 = np.eye(3,3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h3><span style="color:#065a60">E8: Use NumPy to generate a random number between 0 and 1.</span></h3>

In [47]:
arr8 = np.random.rand()
arr8

0.08044096355283992

<h3><span style="color:#065a60">E9: Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
.</span></h3>

In [50]:
arr9 = np.random.randn(5,5)
arr9

array([[ 0.34095927,  0.71261373, -0.3977904 , -1.72234294,  0.09922299],
       [ 0.08069781, -0.24584432, -0.01779087, -2.46489093,  0.54715001],
       [ 1.07001003,  1.07352684, -1.16225486,  1.55978094, -0.19110843],
       [-0.20964517, -1.04293089,  0.15741001, -1.02137556, -0.44653059],
       [-1.63438655,  0.16143041,  0.17658   , -0.42853415, -1.22811631]])

<h3><span style="color:#065a60">E10: Create the following matrix:.</span></h3>

In [52]:
arr10 = np.arange(0.01, 1.01, .01).reshape(10,10)
arr10

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

<h3><span style="color:#065a60">E11: Create an array of 20 linearly spaced points between 0 and 1.</span></h3>

In [53]:
arr11 = np.linspace(0, 1, 20)
arr11

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [54]:
# IDEXING AND SELECTION EXERCISES

mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

<h3><span style="color:#065a60">E12: Write code that reproduces the output shown below..</span></h3>

**Output: array([[12, 13, 14, 15], [17, 18, 19, 20],[22, 23, 24, 25]])**

In [55]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

 <h3><span style="color:#065a60">E13: Write code that reproduces the output shown below.</span></h3>
 
 **Ouput: 20**

In [58]:
mat[3,4]

20

<h3><span style="color:#065a60">E14: Write code that reproduces the output shown below.</span></h3>

**Output: array([[ 2], 
    [ 7], [12]])**

In [59]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

 <h3><span style="color:#065a60">E15: Write code that reproduces the output shown below.</span></h3>

**Output: array([21, 22, 23, 24, 25])**

In [60]:
mat[4]

array([21, 22, 23, 24, 25])

 <h3><span style="color:#065a60">E16: Write code that reproduces the output shown below.</span></h3>

**Output: array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])**

In [61]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

 <h3><span style="color:#065a60">E17: Get the sum of all the values in mat.</span></h3>

In [62]:
mat.sum()

325

 <h3><span style="color:#065a60">E18: Get the standard deviation of the values in mat.</span></h3>

In [63]:
mat.std()

7.211102550927978

 <h3><span style="color:#065a60">E19: Get the sum of all the columns in mat.</span></h3>

In [64]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

<a id=3>  </a> <br>

<h2>Pandas Exercises</h2>

![python](img/pandas.gif)

In [67]:
# import pandas

import pandas as pd

<h3><span style="color:#065a60">Coding Exercise Check-in 4: Labeled Index in Pandas Series </span></h3>
